title: Stephanie's Beginning in Tech Blog
author: Stephanie Pena
email: stephp23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my new 'beginner in tech' blog! 
  I will be sharing bits about myself,
  along with my experiences as I start learning how to code.
  
# social links
github_username:  stephp23
instagram_username:  steph_p_23
show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
#page theme



